"""empty message

Revision ID: 2b6c999bc137
Revises: 5fb7282c3a42
Create Date: 2022-03-09 11:35:55.421112

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '2b6c999bc137'
down_revision = '5fb7282c3a42'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_log', sa.Column('date_time', sa.DateTime(), nullable=True))
    op.drop_column('user_log', 'user_activity')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_log', sa.Column('user_activity', mysql.VARCHAR(length=256), nullable=False))
    op.drop_column('user_log', 'date_time')
    # ### end Alembic commands ###
