"""empty message

Revision ID: 5fb7282c3a42
Revises: 
Create Date: 2022-03-01 08:32:28.289257

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '5fb7282c3a42'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('note', 'date_added',
               existing_type=mysql.DATETIME(),
               nullable=True)
    op.alter_column('note', 'date_modified',
               existing_type=mysql.DATETIME(),
               nullable=True)
    op.alter_column('note', 'reminder',
               existing_type=mysql.DATETIME(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('note', 'reminder',
               existing_type=mysql.DATETIME(),
               nullable=False)
    op.alter_column('note', 'date_modified',
               existing_type=mysql.DATETIME(),
               nullable=False)
    op.alter_column('note', 'date_added',
               existing_type=mysql.DATETIME(),
               nullable=False)
    # ### end Alembic commands ###
