"""empty message

Revision ID: ba4a2857733f
Revises: 29d9d7a0eb9a
Create Date: 2022-02-25 16:38:43.841262

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ba4a2857733f'
down_revision = '29d9d7a0eb9a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('status', sa.Enum('active', 'suspended', 'terminated', name='user_status'), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'status')
    # ### end Alembic commands ###
